# Generated by Django 4.1 on 2022-10-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessionsapp', '0004_post_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
            ],
        ),
    ]
