# Generated by Django 4.1 on 2022-10-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessionsapp', '0008_rename_location_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
