# Generated by Django 4.1 on 2022-10-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessionsapp', '0010_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uni',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
