# Generated by Django 4.1 on 2022-10-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessionsapp', '0011_profile_uni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='confession',
            field=models.CharField(editable=False, max_length=300),
        ),
    ]
